# Generated by Django 5.0.2 on 2024-02-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_appointment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="token",
            field=models.CharField(max_length=100),
        ),
    ]
