# Generated by Django 4.2.3 on 2024-03-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_appointment_attendee_carbooking_carmodel_event_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carbooking",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
