# Generated by Django 5.0.2 on 2024-02-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0004_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_description",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_total_attendees",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
