# Generated by Django 4.2.3 on 2024-02-28 19:00

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0004_attendee_carmodel_event_remove_customer_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("var_type", models.CharField(max_length=100)),
                ("fuel", models.CharField(max_length=100)),
                ("color_n", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("model", models.CharField(max_length=100)),
                ("tot_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fname", models.CharField(max_length=100)),
                ("lname", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                (
                    "file1",
                    models.FileField(
                        storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                        upload_to="uploads/",
                    ),
                ),
                (
                    "file2",
                    models.FileField(
                        storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                        upload_to="uploads/",
                    ),
                ),
                ("paid", models.BooleanField(default=False)),
                ("orderid", models.CharField(max_length=100)),
            ],
        ),
    ]
