# Generated by Django 5.0.2 on 2024-02-17 19:42

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0005_alter_event_event_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="video",
            field=models.FileField(
                blank=True,
                storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(),
                upload_to="tests-videos/",
                validators=[cloudinary_storage.validators.validate_video],
            ),
        ),
    ]
