# Generated by Django 5.0.2 on 2024-02-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0007_attendee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendee",
            name="event",
            field=models.CharField(max_length=200),
        ),
    ]
