# Generated by Django 5.0.2 on 2024-02-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0008_alter_attendee_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="id",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="id",
        ),
        migrations.AlterField(
            model_name="customer",
            name="Email",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="Empemail",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
