# Generated by Django 5.0.2 on 2024-02-19 10:01

import cloudinary.models
import cloudinary_storage.storage
import cloudinary_storage.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0009_remove_customer_id_remove_employee_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("min_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("mileage", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "coverpic",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="carinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_desc", models.TextField(blank=True)),
                ("car_type", models.CharField(max_length=100)),
                (
                    "owning",
                    models.CharField(
                        choices=[
                            ("first_hand", "First Hand"),
                            ("second_hand", "Second Hand"),
                            ("limited_edition", "Limited Edition"),
                        ],
                        max_length=100,
                    ),
                ),
                ("units", models.IntegerField(blank=True, null=True)),
                (
                    "car_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.carmodel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Exterior_1",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
                (
                    "Exterior_2",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
                (
                    "Exterior_3",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
                (
                    "Exterior_4",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
                (
                    "Exterior_5",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
                (
                    "Exterior_6",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
                (
                    "Exterior_7",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
                (
                    "Exterior_8",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
                (
                    "Interior_1",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
                (
                    "Interior_2",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
                (
                    "Interior_3",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
                (
                    "Interior_4",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
                (
                    "Interior_5",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
                (
                    "Interior_6",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
                (
                    "Interior_7",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
                (
                    "Interior_8",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
                (
                    "video_1",
                    models.FileField(
                        blank=True,
                        storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(),
                        upload_to="tests-videos/",
                        validators=[cloudinary_storage.validators.validate_video],
                    ),
                ),
                (
                    "video_2",
                    models.FileField(
                        blank=True,
                        storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(),
                        upload_to="tests-videos/",
                        validators=[cloudinary_storage.validators.validate_video],
                    ),
                ),
                (
                    "car_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.carmodel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="carFuel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Fuel_type_1",
                    models.CharField(
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("hybrid", "Hybrid"),
                            ("electric", "Electric"),
                            ("cng", "CNG"),
                        ],
                        max_length=100,
                    ),
                ),
                ("Fuel_price_1", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "Fuel_type_2",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("hybrid", "Hybrid"),
                            ("electric", "Electric"),
                            ("cng", "CNG"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "Fuel_price_2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "Fuel_type_3",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("hybrid", "Hybrid"),
                            ("electric", "Electric"),
                            ("cng", "CNG"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "Fuel_price_3",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "Fuel_type_4",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("hybrid", "Hybrid"),
                            ("electric", "Electric"),
                            ("cng", "CNG"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "Fuel_price_4",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "Fuel_type_5",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("hybrid", "Hybrid"),
                            ("electric", "Electric"),
                            ("cng", "CNG"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "Fuel_price_5",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "car_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.carmodel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "colorpic1",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
                ("colorname1", models.CharField(max_length=100)),
                (
                    "colorpic2",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
                ("colorname2", models.CharField(max_length=100)),
                (
                    "colorpic3",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
                ("colorname3", models.CharField(max_length=100)),
                (
                    "colorpic4",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
                ("colorname4", models.CharField(max_length=100)),
                (
                    "colorpic5",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
                ("colorname5", models.CharField(max_length=100)),
                (
                    "colorpic6",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
                ("colorname6", models.CharField(max_length=100)),
                (
                    "car_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.carmodel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarTech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Tech_pic1",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
                ("Tech_name1", models.CharField(max_length=100)),
                ("Tech_desc_1", models.TextField(blank=True)),
                (
                    "Tech_pic2",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
                ("Tech_name2", models.CharField(max_length=100)),
                ("Tech_desc_2", models.TextField(blank=True)),
                (
                    "Tech_pic3",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
                ("Tech_name3", models.CharField(max_length=100)),
                ("Tech_desc_3", models.TextField(blank=True)),
                (
                    "Tech_pic4",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
                ("Tech_name4", models.CharField(max_length=100)),
                ("Tech_desc_4", models.TextField(blank=True)),
                (
                    "Tech_pic5",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="media"
                    ),
                ),
                ("Tech_name5", models.CharField(max_length=100)),
                ("Tech_desc_5", models.TextField(blank=True)),
                (
                    "car_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.carmodel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Carvarient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Varient_name_1", models.CharField(max_length=100)),
                ("Varient_desc_1", models.TextField(blank=True)),
                ("Var_price_1", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Varient_name_2", models.CharField(max_length=100)),
                ("Varient_desc_2", models.TextField(blank=True)),
                ("Var_price_2", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Varient_name_3", models.CharField(max_length=100)),
                ("Varient_desc_3", models.TextField(blank=True)),
                ("Var_price_3", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Varient_name_4", models.CharField(max_length=100)),
                ("Varient_desc_4", models.TextField(blank=True)),
                ("Var_price_4", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Varient_name_5", models.CharField(max_length=100)),
                ("Varient_desc_5", models.TextField(blank=True)),
                ("Var_price_5", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "car_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.carmodel"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Generalinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("Delivery_time", models.CharField(max_length=100)),
                (
                    "emi",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "car_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.carmodel"
                    ),
                ),
            ],
        ),
    ]
