# Generated by Django 5.0.2 on 2024-02-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0010_carmodel_carinfo_cargallery_carfuel_carcolor_cartech_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalinfo",
            name="booking_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
